### ISSUE TITLE
realloc has nested critical sections

### ISSUE THREAD

**Issue by devyte** [rhempel/umm_malloc#15]
realloc calls both malloc and free. The code path for malloc is ok, but the code for free has complications. The call to free is within a critical section guarded by UMM_CRITICAL_ENTRY and UMM_CRITICAL_EXIT. The free function body has its own critical section, which means it is nested within the one in the realloc body.
For small(ish) systems, such as the ESP8266, the ENTRY and EXIT guards enable/disable interrupts. In such cases, the code after the EXIT guard in free() and the final EXIT guard in realloc won't be guarded as is expected:
```cpp
realloc()
  //some code
  UMM_CRITICAL_ENTRY //disable interrupts
  //some critical code
  call free()
    //some code
    UMM_CRITICAL_ENTRY //disable interrupts again (does nothing)
    //some critical code
    UMM_CRITICAL_EXIT //enable interrupts (code point A)
    //more code
    return from free()
  //more critical code
  UMM_CRITICAL_EXIT //enable interrupts again (does nothing, code point B)
  //final code
  return from realloc()
```

The code between code points A and B is expected to be guarded because of the ENTRY and EXIT, but it is not.

It is possible to fix this within the ESP compiling environment with a lock class instance for ENTRY, because there umm is being compiled as .cpp. In that case, each class instance saves the previous interrupt state and restores it on destruction. However, that is not viable in other systems where umm is being built as .c.

I think it would be best to implement a fix here by removing the nested critical sections. The solution would be to refactor free() into two functions: an internal unguarded core function, and a wrapper that calls the core function between ENTRY and EXIT guards. Then, the free() call in realloc() would be replaced with the unguarded function.

*Edit:* the code path for malloc is also not ok. While implementing #16 I realized that malloc is also called from within the critical section, so I refactored that as well.

**Comment by rhempel** [comment]
Hey thanks for pointing this out - I am guessing that for systems that take advantage of the critical section lock that this would cause some mystifying errors ;-)
There are a couple of additional things we can do here:
1. Add test cases and dummy code for the macros that will catch nesting errors (there may be others that are worth looking for)
2. Add documentation on how to handle critical sections that simply disable interrupts correctly.

I have been bitten enough times by critical sections that I always look for or write my own nesting handler.

I'll take a look at your suggested code and consider it for inclusion, but I am also busy so it might take a few days to get to it.

Thanks again for your input, and I appreciate the effort you have gone to in suggesting a solution!

**Comment by devyte** [comment]
At the ESP8266 Arduino core we use and appreciate your lib. It's only right to contribute back :)
BTW, the fragmentation metric mentioned by @d-a-v in the other issue has been working quite well for us. I'll see if a PR can be made with that as well.

**Comment by devyte** [comment]
Closing due to commit d33a0f1 and because #16 was superseded and closed.
