### ISSUE TITLE
realloc strategy change

### ISSUE THREAD

**Issue by mhightower83** [rhempel/umm_malloc#17]
I have been working with a very old branch of `umm_malloc` that is in the _Arduino ESP8266_ project. I am in the process of adapting your current version into the project. I have a few thoughts I will share over time. For now, I want to focus on a change I noticed that might have been intentional or an oversight. A little background is needed. In the old version, I saw the comment:
>"Bill Dittman provided excellent suggestions, including macros to support using these functions in critical sections, and for optimizing realloc() further by checking to see if the previous block was free and could be used for the new block size. This can help to reduce heap fragmentation significantly."

Of interest here is the "reduce heap fragmentation". While the top-level comment mentioned this, the code where it happens did not identify that it was doing it. The logic flow was to always try and assimilate up, then look to see if an assimilate down was possible. By always assimilating down when possible it resulted in locally deframenting the allocation. This process also applied to allocations that were being shrunk. This, of course, comes at the price of a memory copy.

After some searching, I found where the enhancement was removed: https://github.com/rhempel/umm_malloc/commit/13008fadec99c2437558018990199305292aec19 (around line 531 of umm_malloc.c left side). The additional code cleanup changed the logic to one of reducing copy on _realloc_.

I can see where some would prefer to reduce memory copy and others would prefer the defragmentation. IMHO for the _Arduino ESP8266_ with very limited heap space, the local defragmentation when possible would be prefered.

**Comment by devyte** [comment]
@rhempel I suppose the question here is: is it possible to provide both behaviors, either simultaneously or at least in a configurable manner?

**Comment by rhempel** [comment]
Step 1 is making a test case and verifying failure which I have done. Next is coming up with a method to handle the configuration of the assimilation strategy. Assimilating down will force a copy which is slower but leaves less fragmentation.

If we agree that in most cases we care more about reducing fragmentation, then I will make this the default.

Now I just need to think of a good name for the configuration flag and then figure out how to make a test case that works correctly depending on how the system is configured.

**Comment by rhempel** [comment]
Well, I have finally got some spare cycles to work on this, and it turns out that the fix was fairly simple and raised a few opportunities for optimization - which I have not yet explored.
The strategy (documented in the umm_realloc() routine) is updated to assimilate up only if the fit is exact, or if the previous block is in use and the new request fits.
This may still leave a bit of fragmentation, but will force a downward assimilation if possible and the upward assimilation is not exact.
