### ISSUE TITLE
umm_malloc_cfg.h conflicts with user's config file

### ISSUE THREAD

**Issue by iwasz** [rhempel/umm_malloc#18]
Hi

   Dunno if this is a bug or feature, but umm_malloc_cfg.h that is committed into your library conflicts with a file created by the user. This way users have to modify your umm_malloc_cfg.h file to change settings or remove it and provide their own somewhere else. And then if the users (like myself) are using your library as a git submodule, git reports modifications to the umm_memory directory which cannot be pushed unless they fork the umm_malloc. I think that only umm_malloc_cfg_example.h should exists in the repo. Please let me know if I'm missing something.

**Comment by devyte** [comment]
Having the umm_malloc_cfg. h in the repo is SOP for configurable libs like this. I'd say you are meant to work off your own fork, especially because you should have your own cfg file under version control.

**Comment by rhempel** [comment]
I have seen this done another way, which is to have a set ofdefault #defines in umm_malloc_cfg.c that are used unless overridden by a user's values in umm_malloc_cfg_board.h
You still want the board level config to be in a board specific folder that is not under git control.
I'll think about this a bit more and get back later.

**Comment by rhempel** [comment]
I will open a new issue to allow the user to override defaults in umm_malloc_cfg.h by including the user's config IF they have made a compile level -D define for the override filename.
