### ISSUE TITLE
malloc readme inconsistency?

### ISSUE THREAD

**Issue by andig** [rhempel/umm_malloc#2]
Trying to understand how the initialization works. In https://github.com/rhempel/umm_malloc/blame/master/README.md#L214 you mention that 

> The current block pointer will be at the end of the free list, and we know we're at the end of the list because the nf index is 0, like this:

In the example just above, https://github.com/rhempel/umm_malloc/blame/master/README.md#L175 the nf index is 1 though:

	   BEFORE                             AFTER

                   nf   pf                            nf   pf
	   +----+----+----+----+              +----+----+----+----+
	0  |  0 |  0 |  0 |  0 |           0  |  1 |  0 |  1 |  0 |
	   +----+----+----+----+              +----+----+----+----+
	   +----+----+----+----+
	1  |  0 |  0 |  0 |  0 |
	   +----+----+----+----+

Is #175 potentially wrong or am i missing something?

**Comment by andig** [comment]
I've noticed, reading through the docs, that the formatting has been broken regading before/after blocks when moving to readme. I'll try to send you a PR.

**Comment by rhempel** [comment]
The initialization and comment is correct - what's happening is that I wanted the library to work without requiring a call to initialize the heap area, assuming that the allocated area is cleared to 0 by the normal runtime startup code. The very first `malloc` needs to handle this and sets up the "head" of the heap to be always pointing at the first block index.
