### ISSUE TITLE
Create a fast metric calculator that just scans the free list

### ISSUE THREAD

**Issue by rhempel** [rhempel/umm_malloc#27]
Make the on-the-fly metric calculation a compileable option, the metric is useful even without a fill-blown umm_info() implementation that can dump the heap structure.

**Comment by rhempel** [comment]
Having on-the-fly metric calculation for the fragmentations sounds like a good idea, but in fact this adds complexity and is rarely worth the speedup.

If you need the fragmentation metric, then it is most likely better to calculate it on demand rather than incurring the overhead of at least two multiplications and 4 additions for each block allocation.

For the test suite, we do 100,000 allocations and there are only 60 items in the free list to scan at the end.

I then considered writing an optimized loop to spin through the free list to collect metrics, but the umm_info() function actually does a good job of it, and if you set the DBGLOG_LEVEL appropriately, then all the logging code is compiled out anyways.

@d-a-v and @devyte do you concur?

The current master branch has code that calculated the fragmentation metric components on the fly, but I feel this adds complexity, overhead, and is incomplete because we cannot track the largest free block without scanning the free list anyways.

**Comment by rhempel** [comment]
Actually, the umm_info() look does look through all the allocated blocks, but I still believe it's quicker and more useful than keeping track of the fragmentation metric on the fly - happy to be proved wrong :-)

**Comment by rhempel** [comment]
See #28 for a pull request that will close this issue

**Comment by d-a-v** [comment]
I see #28 completely removes the on-the-fly calculation which is `UMM_METRICS`-optional.
Could `UMM_METRICS` be instead disabled by default ?
(or another `UMM_METRIC_ON_THE_FLY`-like be used but disabled by default)
Would you let me a chance to try and make some performance tests, both on linux and esp8266 ?

**Comment by rhempel** [comment]
@dav - by all means go ahead and benchmark this in real life from master. I would be very interested to see the results - which is why I have not yet merged in the PR.

**Comment by rhempel** [comment]
I am adding a performance test with timestamps on the individual functions - this requires a minor reorganization of the stress testing to allow testing under different compile conditions.
