### ISSUE TITLE
Pick a code standard and reformat using  standard tool

### ISSUE THREAD

**Issue by rhempel** [rhempel/umm_malloc#35]
This is a low priority task as I need to settle on a code formatting tool and then configure it to meet a reasonable code standard - probably somewhere between the Linux and LLVM standards :-)

**Comment by devyte** [comment]
We use astyle, it's very configurable and can be automated as a checker.

**Comment by rhempel** [comment]
I ended up using uncrustify and used the same config file as the https://github.com/micropython/micropython project. I've spent a LOT of time looking at that code and it does not hurt my eyes or brain.
