### ISSUE TITLE
add stddef.h to umm_malloc.h

### ISSUE THREAD

**Issue by bramankp** [rhempel/umm_malloc#40]
`size_t` is not defined by default and depending on how you build a project that includes umm_malloc, you can run into issues when `umm_malloc.h` tries to use it before `stddef.h` gets included elsewhere.

**Comment by rhempel** [comment]
Great catch - I will fix this on the weekend (hopefully)

**Comment by rhempel** [comment]
Resolved and merged - thanks for the report and suggested fix
