### ISSUE TITLE
heap size

### ISSUE THREAD

**Issue by torbenmoeller93** [rhempel/umm_malloc#42]
Hi
with the "#define UMM_MALLOC_CFG_HEAP_SIZE" I can set the heap size to a user-defined size. However, the heap size is limited to 256kB due to the maximum number of blocks. Is it possible to increase the heap to 1MB or more? Where do I have to make changes to achieve this?
I have read that it is possible to add more data bytes to the body of the memory block at the expense of free block size overhead.
Where can I add more data bytes to the body of the memory block?

**Comment by rhempel** [comment]
Yes, it is possible to change the block size to get a bigger heap, but if you are managing more than 256K of heap and with 32K items, then I might suggest going with your compiler's default memory manager.

If you really want to do this, and can guarantee fewer than 32K items in your heap, then chnage this line in umm_malloc.c

UMM_H_ATTPACKPRE typedef struct umm_block_t {
  union {
    umm_ptr used;
  } header;
  union {
    umm_ptr free;
    **uint8_t data[4];**
  } body;
} UMM_H_ATTPACKSUF umm_block;

The value of 4 here gives a block size of 8 (4 bytes plus 4 bytes for the) used indexes. If you replace 4 with 12 then you get 512K of memory in up to 32K items.

I need to look at this in detail, and clean up the struct definitions and add test cases for different sizes ...

**Comment by torbenmoeller93** [comment]
Thanks for the hint.
I want to use your memory manager with the cjson lib. A printed json object, can be larger than 32K.
Is your memory manager not longer an option if the items are larger than 32K? This would be a pity, because json objects tend to fragment quite fast.

**Comment by rhempel** [comment]
Maybe you misunderstand - the umm_malloc manager can handle up to 32K *items* - an item can be any size up to 32K *blocks* - and a block is currently 8 bytes - but I'll see about changing the block size ...

**Comment by rhempel** [comment]
Pushed UMM-42 to master - check for configurable block size in umm_malloc_cfg.h
