### ISSUE TITLE
BANNER PRINT3R

### ISSUE THREAD

**Issue by Danilchikus** [rhempel/umm_malloc#43]
Hello! I made a "banner print3r" robot according to your instructions from the Lego website. (https://www.lego.com/cdn/cs/set/assets/blt18fd6ecf0dc4d30f/BANNER_PRINT3R.pdf) Can you tell me where to get the PROGRAM for this printer? Thank you for the attention.

**Comment by rhempel** [comment]
Unfortunately no - but if you ask on a LEGO MINDSTORMS Facebook group someone might be able to help ...

--
 Ralph Hempel
 rhempel@hempeldesigngroup.com

**Comment by Danilchikus** [comment]
Thanks for the answer!

**Comment by rhempel** [comment]
Closing as not relevant to umm_malloc - but points for finding me this way :-)
