### ISSUE TITLE
i use the latest commit version, but i encounter the bus access hardfault frequently. help me.

### ISSUE THREAD

**Issue by wkler** [rhempel/umm_malloc#48]
![image](https://user-images.githubusercontent.com/23072751/95807355-8b3a8880-0d3c-11eb-9309-0f21acaf57f6.png)
![image](https://user-images.githubusercontent.com/23072751/95807401-ab6a4780-0d3c-11eb-9d1b-6e5894282014.png)
![image](https://user-images.githubusercontent.com/23072751/95807701-672b7700-0d3d-11eb-9a61-71062988fbf7.png)
![image](https://user-images.githubusercontent.com/23072751/95807420-b8873680-0d3c-11eb-8645-7d232211a8f0.png)
i use the Ozone to debug the hardfault , and i found the reason : above variant is too big which cause the arrary Cross-border access to a outoff memory space. 
i use best fit algorithm, UMM_BLOCK_BODY_SIZE  is (16) and i always alloc 34byte, what reason could cause these number too big ? please help me.

**Comment by wkler** [comment]
solve，i have a pointer access that had a address already freed.

**Comment by rhempel** [comment]
That's often the root cause of this kind of error :-)
In the future, please close any issues that you open and solve yourself - thanks for following up!
