### ISSUE TITLE
dbglog missing (and not submodule?)

### ISSUE THREAD

**Issue by essele** [rhempel/umm_malloc#51]
Hi,

I'm banging my head against a brick wall trying to get the DBGLOG stuff to work ... everything is fine if I put some null defines in to replace it, but it's not part of the repo and doesn't seem to be a submodule???

Previous issues raised suggest it's a submodule and has been documented ... but I've tried a --recurse-submodules clone, and I've also tried a submodule init and submodule update ... but there's nothing! And there's no references anywhere I can find??

What am I missing?

**Comment by mhightower83** [comment]
@essele I think I grabbed the one from the test directory tree when I had this issue.
https://raw.githubusercontent.com/rhempel/umm_malloc/master/test/support/dbglog/dbglog.h

I had to replace `#define DBGLOG_FUNCTION fprintf` with something that was safe to call with interrupts disabled. Very environment-dependent.

**Comment by rhempel** [comment]
In the CI definition file, the paths are set up:

:paths:
  :test:
    - +:test/**
    - -:test/support
  :source:
    - src/**
  :support:
    - test/support/*
    
So dbglog.h automagically gets included from the right place - normally you only need this during testing.

Can I ask you to close this issue if you believe it is solved.

**Comment by rhempel** [comment]
@mhightower83  - thanks for chipping in! I am not working on this too much because I believe it is working - but I _am_ always interested in hearing about interesting applications and suggestions for improvement.

All code can be improved :-)

**Comment by essele** [comment]
Hi Ralph,

I don’t believe this is solved … having just dug around a bit more I did indeed find the dbglog.h file in test/support. However…

The #include in umm_malloc.c, and the DBGLOG_FUNCTION are not conditional in any way, so this file is needed all the time, not just for testing, and therefore if you are embedding umm_malloc in another project (which, lets face it, is the whole point) then you’ll need to ensure that your include paths are sufficient to find dbglog.h

So, whilst it might work for the testing (I haven’t tried this) it certainly doesn’t work as expected when embedding without some work, which at the very least I would have thought should be documented … I’m not the first person to have this problem!

Once working it’s excellent by the way … In my project I’m seeing much lower peak memory utilisation for eLua compared to the standard malloc.

Thanks,

Lee.

**Comment by puzrin** [comment]
@rhempel, problem is with this line https://github.com/rhempel/umm_malloc/blob/9c97c56cb34023652dd0b5dfa60db78549fe660d/src/umm_malloc.c#L51.

To make things easy to use:

- place all sources into `/src`
- place all headers to `/include`

That should be ok to make you repo useable with PlatformIO and so on. https://docs.platformio.org/en/latest/librarymanager/creating.html

I'd suggest to look from another end - make this project usable in PlatformIO. That's obvious and huge added value.

**Comment by rhempel** [comment]
I have pushed in some changes to umm_malloc_cfg.h to document the #defines around DBGLOG a bit better. Does this now meet your needs?

@puzrin - does this help - I don't think we need to separate the code from the includes - but I'm open to good arguments that go beyond a single project like PlatformIO. I'd like to know if the current structure is completely broken form PlatformIO.

@essele - thanks for the feedback on operational umm_malloc - I am glad to hear it's doing the job for your project. I did some work on porting Lua to LEGO MINDSTORMS NXTsome years ago - in fact that's partly why I wrote this allocator in the first place :-)
Please review changes and send along feedback if you think we can close this issue

**Comment by puzrin** [comment]
> @puzrin - does this help - I don't think we need to separate the code from the includes - but I'm open to good arguments that go beyond a single project like PlatformIO. I'd like to know if the current structure is completely broken form PlatformIO.

Everything depends on what you wish. With files in include/src, repo can be added as dependency "as is", via URL. In other case - config may be required to define proper location files. For example https://github.com/PetteriAimonen/libfixmath/blob/master/library.json

The most annoying problem was include of `dbglog/dbglog.h`, but you dimmed it in latest update.

**Comment by essele** [comment]
Hi Ralph,

It's difficult for me to test the updates at the moment, I will get to that soon, however having looked at the approach you've taken with DBGLOG it looks like it should be fine. I'll close now and open another issue if there are still problems.

Many thanks,

Lee.
