### ISSUE TITLE
Inconsistently fails for oversized allocation requests

### ISSUE THREAD

**Issue by user2222222222** [rhempel/umm_malloc#62]
I understand this won't generally be an issue for the intended use of this library, but it did cause me some trouble and think it's worth fixing.  The reason it's an issue for me is that (for my application) large allocations must fail when requested of umm before the system moves on to another memory manager.

The issue is that when size_t is 32bit, umm_blocks() will overflow for larger block sizes:
uint16_t umm_blocks(size_t size)

So with my umm configuration, if I request 8MB from umm (which, obviously it can't and shouldn't serve), it will succeed and return a ptr to some unknown chunk size.

The simple solution for me was to make umm_blocks() return zero when size is out of range.

I replaced this line:
    return 2 + size / (UMM_BLOCKSIZE);
With this:
    size /= (UMM_BLOCKSIZE);
    if (size > 0xFFFF-2) {
    	return 0;
    }
    return 2 + size;

Then test for zero as an error condition in alloc cores:
    blocks = umm_blocks(size);
    if (blocks == 0)
    	return (void *)NULL;

**Comment by rhempel** [comment]
Ummm - thanks for raising this issue, and I’m embarrassed that I did not consider this obvious failure mode.

Also thanks for the proposed fix - I’ll add a test case as well :-)

I’m not sure when it will be fully fixed but I expect it will be before the end of the holidays

**Comment by rhempel** [comment]
Fixed in v1.1.1 release - thanks for the report!
- added test cases for this failure mode (plus a few more around the limits of block index)
Note that we do not need to check the number of blocks returned - the allocator already handles requests for more than it is able to deliver. All we had to do is return 32767 (INT16_MAX) to get the correct behaviour because even with a maximally sized block available, there must be 2 blocks allocated for the first and last bookkeeping blocks :-)

**Comment by rhempel** [comment]
@user2222222222 - can I ask what your use case is for this library - I'm collecting real-world examples to add to the documentation

**Comment by user2222222222** [comment]
Sorry for not getting back to you: this isn't email I normally keep up on.
I'm using umm for memory defragmenting on a Palm Pilot.  Palm OS needs to make known and predictable system allocations that progressively fragment the main heap.  Eventually, the system becomes unstable resulting in dreaded random system resets.
To fix the problem, a small umm heap can conveniently be allocated within the main heap.  These non-movable system allocations can then be redirected to the umm "safe-zone" which prevents the main heap from fragmenting.  
In the rare case where the main heap is depleted, it reverts back to umm for emergency help.  This is where umm was saying "no problem, here you go" when it should have been failing.
