### ISSUE TITLE
Warnings

### ISSUE THREAD

**Issue by ademyankov** [rhempel/umm_malloc#7]
VS2017RC: there are 17 warnings for x86 and 25 warnings for x64

**Comment by rhempel** [comment]
I am happy to review PRs that fix the issue, but I am not planning to build for VS2017

**Comment by ademyankov** [comment]
I cannot believe that you don't see those! Those are pretty nasty warnings which should not be related to a specific compiler! I use /W4 setting for VS compiler but gcc is known to be even more picky.

umm_info.c(55): warning C4267: '+=': conversion from 'size_t' to 'unsigned short', possible loss of data
umm_info.c(61): warning C4267: '+=': conversion from 'size_t' to 'unsigned short', possible loss of data
umm_info.c(64): warning C4267: '=': conversion from 'size_t' to 'unsigned short', possible loss of data
umm_info.c(87): warning C4267: '+=': conversion from 'size_t' to 'unsigned short', possible loss of data
umm_info.c(107): warning C4267: '+=': conversion from 'size_t' to 'unsigned short', possible loss of data
umm_info.c(108): warning C4267: '+=': conversion from 'size_t' to 'unsigned short', possible loss of data
umm_info.c(111): warning C4267: '=': conversion from 'size_t' to 'unsigned short', possible loss of data
umm_malloc.c(112): warning C4267: 'return': conversion from 'size_t' to 'unsigned short', possible loss of data

**Comment by rhempel** [comment]
I will look again at my compiler settings and ensure I have all warnings enabled - most of these can be dealt with using proper typecasts

**Comment by rhempel** [comment]
Building with `gcc` on a Debian64 VM these are my `CFLAGS`:
```
CFLAGS  := -c -Wall -Wno-unknown-pragmas -O2 -fPIC -std=gnu99
```
and once I fixed up the warning about lacking prototypes for `memset` the code compiles clean - which is what I thought it would do.

The root cause of the issue is that `unsigned short` is the standard C size that is guaranteed to be exactly 2 bytes on any platform - yes we could make it explicit with `uint_16t` but you will still get the warnings in your case because the compiler is doing you a favour by letting you know that you are truncating the `size_t` from 8 bytes on a 64bit system to 2 bytes.

I will be pushing in some changes that include a potential fix for this and #8 so you should be able to build cleanly.

**Comment by ademyankov** [comment]
Thanks Ralph.
I got a few other issues with Keil5 + ARM v.5.06 update 4 (build 422):
```
compiling umm_malloc.c...
..\..\..\..\src\arm\umm_malloc.c(52): error:  #1032: Definition of nested anonymous union in packed "struct umm_block_t" must be __packed
    } header;
..\..\..\..\src\arm\umm_malloc.c(56): error:  #1032: Definition of nested anonymous union in packed "struct umm_block_t" must be __packed
    } body;
```

For those two I had to add `__pack ` in the declaration of the unions; But that is probably Keil specific crap! I guess?!

But the next one, you should probably see it on all compilers:
```
..\..\..\..\src\arm\umm_malloc.c(601): warning:  #1293-D: assignment in condition
      if( (ptr = umm_malloc( size )) ) {
```

**Comment by ademyankov** [comment]
BTW, that warning `..\..\..\..\src\arm\umm_malloc.c(601): warning:  #1293-D` forced me to read the comment before the `if` and whether the comment or the code is not accurate.

**Comment by rhempel** [comment]
OK, so I found a reference as to why there's an issue for this:
http://community.silabs.com/t5/Bluetooth-Wi-Fi/BT121-with-ARM-cortex-M4-STM32/td-p/160587

I will push in a change that should fix the problem, but I am puzzled as to why I'm not seeing it on my gcc build

**Comment by rhempel** [comment]
@ademyankov - please review the changes - you may have to update `umm_malloc_cfg.h` to add a `#define` to support the correct packed attributes for your compiler - just add the correct `#ifdef# that checks for your compiler variant,

**Comment by ademyankov** [comment]
@rhempel - thank you, I did exactly that for vs2017
`umm_malloc.c(601): warning:  #1293-D: assignment in condition`
is still there

**Comment by rhempel** [comment]
I struggled with the semantics of a failed reallocate and decided that freeing the memory was ok but I'm not convinced yet.
I guess that as long as you are checking the return value you know that it failed and it would be good to still have the old memory.

**Comment by rhempel** [comment]
Well, I was definitely wrong - realloc() does NOT free the original block of memory if the new malloc() fails. @ademyankov I have pushed into this bench another change that fixes the realloc() issue you pointed out - thanks for persisting on this issue and helping to make the library better.

If you agree with the changes then close this issue and I will merge into `master`

**Comment by ademyankov** [comment]
@rhempel Thanks! I am really happy that I was able to contribute just a little bit into your awesome library.
