### ISSUE TITLE
dbglog.h is missing

### ISSUE THREAD

**Issue by ademyankov** [rhempel/umm_malloc#8]
Compiler build error! There was a comment somewhere in the commits that macros from dbglog.h are moved to umm_malloc.c. It is not the case. The folder c-helper-macros is emply in the original repo.

**Comment by rhempel** [comment]
Did you do a
```
git submodule init
git submodule update
```

**Comment by ademyankov** [comment]
Yep! Thanks! Now, I got it. But just for the sake of argument, how I would suppose to know about submodules? Maybe it's a good idea to add something extra info on the project's description page.

**Comment by rhempel** [comment]
Thanks for pointing out missing documentation - I will update when I have some time

**Comment by rhempel** [comment]
@ademyankov - can you verify that the README is clear regarding submodules and then close this issue if you agree?

**Comment by ademyankov** [comment]
It's absolutely clear. Thanks Ralph.
